version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: on-failure
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.domain=graphqltest.crvx.fr'
      - 'traefik.basic.frontend.rule=Host:graphqltest.crvx.fr'
      - 'traefik.basic.port=4466'
      - 'traefik.basic.protocol=http'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
    networks:
      - default
      - web

  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

networks:
  web:
    external: true

volumes:
  mysql:
